# Model
model_name_or_path: swiss-ai/Apertus-8B-Instruct-2509
attn_implementation: eager
torch_dtype: bfloat16

# Dataset
dataset_name: HuggingFaceH4/Multilingual-Thinking
dataset_num_proc: 12

# Hyperparameters
learning_rate: 2.0e-5
gradient_checkpointing: true
num_train_epochs: 1.0
logging_steps: 1
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
max_length: 4096
warmup_ratio: 0.03
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
output_dir: gpt-oss-20b-multilingual-reasoner
report_to: "none"
seed: 42